apiVersion: v1
kind: Service
metadata:
  name: hybrid-sv
  labels:
    app: hybridsv
spec:
  selector:
    app: hybrid
  ports:
    - name: svc
      protocol: TCP
      port: 80
      targetPort: 1111