apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.18.4
clusterName: kubernetes
networking:
  dnsDomain: cluster.local
  podSubnet: 179.10.0.0/16
  serviceSubnet: 179.20.0.0/16
controllerManagerExtraArgs:
  horizontal-pod-autoscaler-use-rest-clients: "true"
  horizontal-pod-autoscaler-sync-period: "10s"
  node-monitor-grace-period: "10s"